name: test
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: juliangruber/find-pull-request-action@master
        id: find-pull-request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
      - run: echo "Your Pull Request has number ${number}"
        if: success() && steps.find-pull-request.outputs.number
        env:
          PR: ${{ steps.find-pull-request.outputs.number }}
